(ns nido.session.services.config-file
  (:require
   [babashka.fs :as fs]
   [clojure.string :as str]
   [nido.core :as core]
   [nido.session.context :as ctx]
   [nido.session.service :as service]))

(def ^:private nido-marker ";; AUTO-GENERATED by nido — do not edit\n")

(defn- write-config! [path data format]
  (case format
    :edn (spit path (str nido-marker (pr-str data) "\n"))
    (throw (ex-info "Unsupported config-file format" {:format format}))))

(defmethod service/start-service! :config-file
  [service-def session-ctx _opts]
  (let [{:keys [path template format backup?]
         :or {format :edn backup? true}} service-def
        project-dir (get-in session-ctx [:session :project-dir])
        full-path (str (fs/path project-dir path))
        backup-path (str full-path ".nido-backup")]

    ;; Backup existing file
    (when (and backup? (fs/exists? full-path))
      (let [content (slurp full-path)]
        (when-not (str/starts-with? content nido-marker)
          (core/log-step (str "Backing up existing " path " to " (str path ".nido-backup")))
          (fs/copy full-path backup-path {:replace-existing true}))))

    ;; Substitute templates and write
    (let [resolved (ctx/substitute session-ctx template)]
      (core/log-step (str "Writing " path))
      (write-config! full-path resolved format))

    {:state {:path full-path :backup-path backup-path :had-backup? backup?}
     :context {}}))

(defmethod service/stop-service! :config-file
  [_service-def saved-state]
  (let [{:keys [path backup-path had-backup?]} saved-state]
    (when had-backup?
      (if (fs/exists? backup-path)
        (do
          (core/log-step (str "Restoring original " (fs/file-name path) " from backup"))
          (fs/move backup-path path {:replace-existing true}))
        (when (fs/exists? path)
          (let [content (slurp path)]
            (when (str/starts-with? content nido-marker)
              (core/log-step (str "Removing nido-generated " (fs/file-name path)))
              (fs/delete path))))))))

(defmethod service/service-status :config-file
  [_service-def saved-state]
  (let [{:keys [path]} saved-state]
    {:alive? (fs/exists? path)
     :path path}))
